const API_METHOD_GET = "GET";
const API_METHOD_POST = "POST";
const API_METHOD_PUT = "PUT";
const API_METHOD_DELETE = "DELETE";

export const API_METHODS = {
  [API_METHOD_GET]: API_METHOD_GET,
  [API_METHOD_POST]: API_METHOD_POST,
  [API_METHOD_PUT]: API_METHOD_PUT,
  [API_METHOD_DELETE]: API_METHOD_DELETE,
};
